### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by valbuilds** [the-nemz/metro-dreamin#164]
When the options `local bus` or `BRT/tram` type is selected for a line, it should auto-follow roads.

Also, it would be nice if I could add a waypoint without it messing up my route. See example below:

https://user-images.githubusercontent.com/69707286/228100824-bc41a95c-3e7d-4c1b-9a9e-40da00289fda.mp4

**Comment by the-nemz** [comment]
Hello, I have updated the station addition algorithm to make the placement much more intuitive :)
