### ISSUE TITLE
Request: Alternate contact method in README

### ISSUE THREAD

**Issue by alex-wenzel** [the-nemz/metro-dreamin#171]
Hello, thanks for maintaining this great site! I had an account-specific issue and tried to DM the `@MetroDreamin` Twitter account, but Twitter has a new policy that users can't DM an account that doesn't follow them unless the user is a paid subscriber. In light of these and other changes at Twitter, I'd suggest establishing another contact method, perhaps an email address. Thanks!

**Comment by the-nemz** [comment]
Long overdue, but an email link has now been added to the README as well as the footer of the website. Thanks!
