### ISSUE TITLE
Request: Change the maps software use in MetroDreamin'

### ISSUE THREAD

**Issue by rklamundao1** [the-nemz/metro-dreamin#174]
Although MetroDreamin' is really great in terms of functionality. One of the problem I encounter is that there are lack of options of using the maps software which is MapBox such as having satellite mode, terrain mode, traffic mode, and others. What we need to do is to theer should be features on the maps software I mention which is replacing MapBox to Google Maps. Also, there are many places in MapBox are inaccurate in terms in some roads in rural area. I recommended to replace MapBox to Google Maps. Google Maps are most preferable to use in terms of creating any type of projects. Also, better to not include the street map view to avoid some possible crashes. Also, add another type of layer with its own estimated time which is tram as some of the pro-commuters advocate needs most of urban areas with tram. Thank you!
![screenshot-20231015-195457](https://github.com/the-nemz/metro-dreamin/assets/147981972/f23500e0-39a6-449c-9275-0dda505fd6b9)

**Comment by the-nemz** [comment]
Hello! While I do not plan on moving MetroDreamin' away from Mapbox, I am planning on incorporating additional map layers at some point in the mid-term future including satellite and topographic. Mapbox has been a very supportive partner of MetroDreamin'.

**Comment by rklamundao1** [comment]
Oh. Thank you so much for giving me an update about.

**Comment by the-nemz** [comment]
Hello! I just added satellite, topographic, and railway layers to the map!
