### ISSUE TITLE
Feature request: Add Automatic Ridership Calculation. 

### ISSUE THREAD

**Issue by Simha-Kalimipalli** [the-nemz/metro-dreamin#183]
Hi There, 

A good feature to add is the approximate ridership of the  generated lines. This could be calculated using the gravity formula 
 - with the density data that is available for each stop in MetroDreamin . Ie calculate approx. ridership that is proportional to (constant)*(magnitude of node 1 density)(magnitude of node 2 density)/(distance between two nodes)^2.

I'm working on an open source package that does for mock origin-destination data and would love to integrate that functionality into MetroDreamin.
Thanks

**Comment by the-nemz** [comment]
I definitely want to add this functionality and plan to do so at some point! Can you explain a bit about what node 1 and node 2 are in this formula?

And please link me to your open source package! I'd love to take a look

**Comment by Simha-Kalimipalli** [comment]
Node 1 and Node 2 are the magnitude of any two given stations. The magnitude can either be represented by the density score or the number of nearby buildings (given when you click a station).

As for my package, I'm still adding the finishing touches (uploading newest version to pypi etc). I will notify you when I finish it!

Here a quick graphic of what a gravity feature could look like:
![image](https://github.com/the-nemz/metro-dreamin/assets/69992738/41a7fad2-1c5a-4342-ab27-d30ce7c409fa)


The concept for gravity is that the total ridership of a line is proportional to the sum of the gravity of all origin destination pairs on the line

**Comment by the-nemz** [comment]
Really interesting idea to visually represent ridership by using the thickness of the line! Thanks for the explanation. I'll think about how I can go about implementing this in the future.

Looking forward to seeing your code!

**Comment by erkinalp** [comment]
i would love this feature, it will make this application far more popular than it is

**Comment by the-nemz** [comment]
@Simha-Kalimipalli In case you haven't seen yet, a ridership calculation was released over the summer :)
