### ISSUE TITLE
Feature request: add different styles of lines

### ISSUE THREAD

**Issue by bfk-pd** [the-nemz/metro-dreamin#227]
It would be really great to have more styles of lines other than just plain (e.g.: DLR is painted differently on Underground maps)
It would also be nice to be able to change line width

**Comment by the-nemz** [comment]
Yes, I am planning to add this feature in an upcoming release :)

**Comment by the-nemz** [comment]
@bfk-pd In case you haven't seen yet, line icons were added earlier this year so you can now use circles, diamonds, stars, hearts, or pluses as the line pattern
